# Generated by Django 4.1.6 on 2023-02-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dat_posted',
            new_name='date_posted',
        ),
    ]
